[package]
name = "simple-assembler"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = "0.15.0"
miette = { version = "7.4.0", features = ["fancy"] }
thiserror = "2.0.11"

[dev-dependencies]
rusty-hook = "^0.11.2"
