[package]
name = "simple-assembler"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = { version = "0.15.0", features = ["debug"] }

[dev-dependencies]
rusty-hook = "^0.11.2"
pretty_assertions = "1"
